### ISSUE TITLE
panic when the server sends GOAWAY

### ISSUE THREAD

**Issue by ameshkov** [ameshkov/gocurl#23]
```
panic: http2: server sent GOAWAY and closed the connection; LastStreamID=2147483647, ErrCode=unknown error code 0x64, debug=""

goroutine 1 [running]:
github.com/ameshkov/gocurl/internal/output.(*Output).Write(0x1400000e660, 0x1400021c000?, 0x104c9e801?)
	github.com/ameshkov/gocurl/internal/output/output.go:66 +0xfc
github.com/ameshkov/gocurl/internal/cmd.Main()
	github.com/ameshkov/gocurl/internal/cmd/cmd.go:83 +0x3f0
main.main()
	github.com/ameshkov/gocurl/main.go:7 +0x1c
```

**Comment by ameshkov** [comment]
Was caused by `gocurl` not being able to read the full body when `--json-output` is specified, now fixed
